<?php
declare(strict_types=1);

// BranchCrossEventsExport SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BranchCrossEventsExportUtility::setRegistrar(function (BranchCrossEventsExportUtility $u): void {
    $u->clean = [BranchCrossEventsExportClean::class, 'call'];
    $u->done = [BranchCrossEventsExportDone::class, 'call'];
    $u->make_error = [BranchCrossEventsExportMakeError::class, 'call'];
    $u->feature_add = [BranchCrossEventsExportFeatureAdd::class, 'call'];
    $u->feature_hook = [BranchCrossEventsExportFeatureHook::class, 'call'];
    $u->feature_init = [BranchCrossEventsExportFeatureInit::class, 'call'];
    $u->fetcher = [BranchCrossEventsExportFetcher::class, 'call'];
    $u->make_fetch_def = [BranchCrossEventsExportMakeFetchDef::class, 'call'];
    $u->make_context = [BranchCrossEventsExportMakeContext::class, 'call'];
    $u->make_options = [BranchCrossEventsExportMakeOptions::class, 'call'];
    $u->make_request = [BranchCrossEventsExportMakeRequest::class, 'call'];
    $u->make_response = [BranchCrossEventsExportMakeResponse::class, 'call'];
    $u->make_result = [BranchCrossEventsExportMakeResult::class, 'call'];
    $u->make_point = [BranchCrossEventsExportMakePoint::class, 'call'];
    $u->make_spec = [BranchCrossEventsExportMakeSpec::class, 'call'];
    $u->make_url = [BranchCrossEventsExportMakeUrl::class, 'call'];
    $u->param = [BranchCrossEventsExportParam::class, 'call'];
    $u->prepare_auth = [BranchCrossEventsExportPrepareAuth::class, 'call'];
    $u->prepare_body = [BranchCrossEventsExportPrepareBody::class, 'call'];
    $u->prepare_headers = [BranchCrossEventsExportPrepareHeaders::class, 'call'];
    $u->prepare_method = [BranchCrossEventsExportPrepareMethod::class, 'call'];
    $u->prepare_params = [BranchCrossEventsExportPrepareParams::class, 'call'];
    $u->prepare_path = [BranchCrossEventsExportPreparePath::class, 'call'];
    $u->prepare_query = [BranchCrossEventsExportPrepareQuery::class, 'call'];
    $u->graphql_body = [BranchCrossEventsExportGraphql::class, 'body'];
    $u->graphql_errors = [BranchCrossEventsExportGraphql::class, 'errors'];
    $u->result_basic = [BranchCrossEventsExportResultBasic::class, 'call'];
    $u->result_body = [BranchCrossEventsExportResultBody::class, 'call'];
    $u->result_headers = [BranchCrossEventsExportResultHeaders::class, 'call'];
    $u->transform_request = [BranchCrossEventsExportTransformRequest::class, 'call'];
    $u->transform_response = [BranchCrossEventsExportTransformResponse::class, 'call'];
});
